name: Update apolo-flow action tags
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -U "PyGithub==2.5.0"
      - id: run_updater
        name: Run update actions script
        run: python update_actions.py ".apolo/*.y*ml"
      - id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: update/actions-tags
          title: Auto-update actions tags
          commit-message: Auto-update apolo-flow actions tags
          body: |
            Updated apolo-flow action version tags in the following
            files: ${{ steps.run_updater.outputs.updated_files }}
